before_script:
    - apt-get -q update
    - apt-get -y install python3
    - apt-get install -y python3-pip
    - pip3 install -q httpbin
    - pip3 install -q gunicorn
    - gunicorn -b 127.0.0.1:8000 -b unix:httpbin.sock httpbin:app&

OTP-23:
    image: erlang:23

    script:
    - ./support/rebar3 eunit
    - ./support/rebar3 dialyzer

